[cli]
bin = "/usr/bin/kvm"
img = "/usr/bin/qemu-img"
genisoimage = "/usr/bin/genisoimage"

[ovmf]
code = "/usr/share/OVMF/OVMF_CODE_4M.fd"
vars = "/usr/share/OVMF/OVMF_VARS_4M.fd"

[api]
groups = ["yave"]
listen = "localhost:3000"
