[package]
name = "yave"
version = "0.1.0"
edition = "2024"

[dependencies]
json = "0.12.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
